name: Release & Publish

on:
  push:
    tags:
      - "v*"
  workflow_call:
  workflow_dispatch:

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          draft: false
          prerelease: false

  publish-pnpm:
    name: Publish to NPM (using pnpm)
    runs-on: ubuntu-latest
    # Skip this step in forks
    if: ${{ github.repository_owner == 'JonathanSchndr' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm' # Caching pnpm modules

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest # or specify a version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile && pnpm run build # --frozen-lockfile ensures consistent installs

      - name: Publish packages to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
          pnpm publish --access public --no-git-checks
